kotlin.code.style=official

# Project configuration
group_name = com.mattmx
id = nametags
version = 1.6.0

plugin_name = NameTags
plugin_main_class_name = NameTags
plugin_author = MattMX
loader = com.mattmx.nametags.NameTagsLoader

include_commit_hash = true

# Cross-platform JDK discovery/provisioning for toolchains
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.fromEnv=JAVA_HOME,JDK21_HOME
